// Code generated by "stringer -type LogLevel ."; DO NOT EDIT.

package kif

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEBUG-10]
	_ = x[INFO-20]
	_ = x[WARN-30]
	_ = x[ERROR-40]
	_ = x[FATAL-50]
	_ = x[PANIC-60]
}

const (
	_LogLevel_name_0 = "DEBUG"
	_LogLevel_name_1 = "INFO"
	_LogLevel_name_2 = "WARN"
	_LogLevel_name_3 = "ERROR"
	_LogLevel_name_4 = "FATAL"
	_LogLevel_name_5 = "PANIC"
)

func (i LogLevel) String() string {
	switch {
	case i == 10:
		return _LogLevel_name_0
	case i == 20:
		return _LogLevel_name_1
	case i == 30:
		return _LogLevel_name_2
	case i == 40:
		return _LogLevel_name_3
	case i == 50:
		return _LogLevel_name_4
	case i == 60:
		return _LogLevel_name_5
	default:
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
